### ISSUE TITLE
Dropbearのサーバに接続出来ない

### ISSUE THREAD

**Issue by ttdoda** [poderosaproject/poderosa#18]
接続先が Dropbear http://matt.ucc.asn.au/dropbear/dropbear.html のサーバの時、
"接続先はSSHのサーバではありません。" というダイアログが表示されて接続出来ない。

サーバ: Dropbear v2015.71
クライアント: Poderosa 4.3.16

telnetコマンドでDropbearのサーバに接続すると、Server側がidentification stringを送って来た後
クライアントのidentification stringを待たずにKEXINITパケットを送ってくるのが観測できる為、
その影響が考えられる。

ただし、Dropbear v2012.55 という古いバージョンでは上記のKEXINITパケットを先に送ってくるという挙動は
確認出来ないが、"failed to verify" というダイアログが表示されて接続出来ない為、他にも問題がある可能性がある。

**Comment by poderosaproject** [comment]
サーバからのバージョン情報の読み込み方を変更して、後続のパケットに影響が出ないようにしました。
2de050ea47a09830f79eef54f32492aafb2b55e3
