### ISSUE TITLE
mono support

### ISSUE THREAD

**Issue by alon** [poderosaproject/poderosa#20]
Hi,

 Is there any chance you will support mono?

 Specifically what is stopping mono support is tie in directly to windows dlls - user32.dll, kernel32.dll, at Plugin/Win32.cs

 Or is it possible to disable the usage of that plugin and not suffer?

 Thanks,

Alon

**Comment by poderosaproject** [comment]
Poderosa uses Win32 API for drawing text.
It is a core functionality and cannot be disabled.
