### ISSUE TITLE
X11 forward not work

### ISSUE THREAD

**Issue by minico** [poderosaproject/poderosa#25]
X11 forward not work

**Comment by minico** [comment]
OK, I tried the latest code, it seems work, but need a little code change.

**Comment by poderosaproject** [comment]
User interface for setting X11 forwarding is not yet provided.
I haven't decided the user interface yet.
X11 forwarding should be enabled in the connection options, not by default.

**Comment by minico** [comment]
thank you, it's a big feature that poderosa had been lacked compared with other products like securecrt.
now,I can throw securecrt away:)

**Comment by poderosaproject** [comment]
SSH/TELNET dialog was renewed.
Options for X11 forwarding are available on it.

890eb2368c73cb60bd8ebe4ef953609e92265dd8...fbd676ef765cea36ae7fe3daacabddfb5d355f3d
