### ISSUE TITLE
About the function "Open pipe" in "File" menu

### ISSUE THREAD

**Issue by minico** [poderosaproject/poderosa#27]
I found the function long ago, but I didn't know how to use it?
could you please give an example?
Thank you.

**Comment by poderosaproject** [comment]
"Process" runs an application and connects application's stdin and stdout to Poderosa with pipes.
If the application wrote something to its stdout, Poderosa's terminal displays it.
If user inputs something to the terminal, the application gets it from its stdin.
If you want to try, specify "C:\Windows\System32\cmd.exe" and turn the local-echo on.

"Named pipe" opens Windows' named pipe.
Named pipe has to be already created by other application.
For example, VMware or VirtualBox expose the other end point of the virtual serial port connection as a named pipe.
By opening such named pipe, Poderosa can communicate with another application in the virtual machine through the virtual serial port connection.

**Comment by minico** [comment]
It sound greate that I can run cmd in Poderosa.
But after tried, I found it doesn't work as expected.
When I tried "C:\Windows\System32\cmd.exe", 
a terminal will be opened and show the following outputs:

> Microsoft Windows [ 10.0.14393]
> (c) 2016 Microsoft CorporationȨ
> 
> C:\Windows\System32>

but the terminal doesn't accept my inputs.
I input "dir" and "Enter", there is no response.

**Comment by poderosaproject** [comment]
Did you try enabling local echo and CR+LF new-line setting ?

**Comment by minico** [comment]
Great! It works after I change “new-line” to "CR+LF“.
But,  the behavior is little strange when moving cursor via arrow key or backspace key.
