### ISSUE TITLE
Immediate disconnect after SSH login

### ISSUE THREAD

**Issue by j-lang** [poderosaproject/poderosa#29]
Poderosa is my favorite ssh client for years for configuring webservers. Since around 2 weeks ssh connections are dropped immediately  after connecting to webserver of internet provider or on first input.
User password and keys are correct, checked in event.log and with support of provider. 
If connecting with putty or poderosa 5, there is no problem -> provider does not like to make further analysis but confirms correct setup
The issue is on 3 different PCs, they worked with poderosa perfect til now. Uninstall and new installation did not change this problem.  
Version : 4.3.16
CLR     : 4.0.30319.42000
Windows 10 Pro 64bit

**Comment by poderosaproject** [comment]
Which version of SSH server is running on the remote host?
The latest OpenSSH disables old algorithms by default, but Poderosa 4.3.x still uses them.

If you interested, try 4.4.0-dev. It accepts ECDSA or ED25519.
https://sourceforge.net/projects/poderosa/files/releases/4.4.0-dev-snapshot/Poderosa-4.4.0-dev-20170118-bin.zip/download

**Comment by j-lang** [comment]
4.4.0 snapshot works! 
Thank you
