### ISSUE TITLE
SourceForge dead link

### ISSUE THREAD

**Issue by drewnoakes** [poderosaproject/poderosa#34]
In the README this link is dead:

https://poderosa.sourceforge.net/

**Comment by poderosaproject** [comment]
I fixed url in da6a0512d510fc5f02f065a33727f4bbff19a8cb. Thank you.

**Comment by drewnoakes** [comment]
The link is still dead for me. Tested in several browsers. IP address is fine, but connection is refused by the host, regardless of HTTP/HTTPS scheme.
