### ISSUE TITLE
Github or Sourceforge or both ?

### ISSUE THREAD

**Issue by ssinfod** [poderosaproject/poderosa#35]
Hello, 

Is ponderosa project source code on sourceforge or github ?

I see the project here:
https://sourceforge.net/projects/poderosa/
https://sourceforge.net/p/poderosa/code

but there is also source code from this github
https://github.com/poderosaproject/poderosa/ 

Where is the latest version of the source code ?
Thanks

**Comment by poderosaproject** [comment]
The latest source code is maintained on GitHub.

SourceForge is used for web hosting, file hosting, and forums.
